/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarSelect: typeof import('./src/components/CalendarSelect.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LocationSelect: typeof import('./src/components/LocationSelect.vue')['default']
    NzSVG: typeof import('./src/components/nzSVG.vue')['default']
  }
}
